### ISSUE TITLE
docs not clear

### ISSUE THREAD

**Issue by simplehumble** [trajano/docker-volume-plugins#13]
In the following option: its not super clear what values can be for store1,store2

docker plugin install --alias PLUGINALIAS \
  trajano/glusterfs-volume-plugin \
  --grant-all-permissions --disable
docker plugin set PLUGINALIAS SERVERS=store1,store2
docker plugin enable PLUGINALIAS

Is that IP of node? is that volume name? Can you give real life example?

**Comment by trajano** [comment]
any DNS name.  store1 and store2 are my real life examples because those are my storage servers's host names.
