### ISSUE TITLE
docker stop command create <defunct> process

### ISSUE THREAD

**Issue by btheu** [trajano/docker-volume-plugins#29]
Every time a container having a glusterfs docker volume mounted is stopped, a daemon process typed as \<defunct\> is created.

> docker run --rm -it -v my-glusterfs-volume:/work alpine

After a control-c, ps aux shows defunct. This is what ps command shows after 6 starts and stops.

> root     24438  0.0  0.0      0     0 ?        Zs   11:04   0:00 [glusterfs] \<defunct\>
> root     24560  0.0  0.0      0     0 ?        Zs   11:04   0:00 [glusterfs] \<defunct\>
> root     24801  0.0  0.0      0     0 ?        Zs   11:05   0:00 [glusterfs] \<defunct\>
> root     25263  0.0  0.0      0     0 ?        Zs   11:07   0:00 [glusterfs] \<defunct\>
> root     25381  0.0  0.0      0     0 ?        Zs   11:08   0:00 [glusterfs] \<defunct\>
> root     25529  0.0  0.0      0     0 ?        Zs   11:08   0:00 [glusterfs] \<defunct\>

Regards,

**Comment by ximon18** [comment]
FYI I see the same issue with `mwmahlberg/glusterfs-volume-plugin`.
I tried to reproduce with `sapk/docker-volume-gluster` but hit https://github.com/sapk/docker-volume-gluster/issues/34.
FYI I'm using `glusterfs-server 3.13.2-1ubuntu1` on Ubuntu 18.04.
As I can reproduce this creation of defunct glusterfs processes with another Docker volume plugin I wonder is this a GlusterFS issue or are both plugins misusing GlusterFS in the same way?

**Comment by ximon18** [comment]
Note: mounting and unmounting via an /etc/fstab entry and writing to the mount point does not cause the defunct process count to increase.

**Comment by ximon18** [comment]
So, as far as I can work it out it seems that this plugin executes a command to do the mount, which looks like `glusterfs -s <servername> --volfile-id=<glusterfs_vol_name> </mount/point>` where the mount point is something to do with a `DefaultDockerRootDirectory`. If I execute such a command on my host myself, first making sure that the target mount point directory exists, then indeed I get a successful GlusterFS mount, and a background `glusterfs` process. If I kill that process I do not get left with a defunct process.

**Comment by ximon18** [comment]
Passing `--no-daemon` to the trajano glusterfs plugin causes container creation to block in `Creating` state unsurprisingly. FYI I used this command:
```
docker volume create -d glusterfs:v2.0.3 -o glusteropts="-s xxx --volfile-id=gfs --no-daemon" gfs
```

**Comment by ximon18** [comment]
I'm attempting to modify the plugin to store the pid then kill it instead of calling unmount. Will let you know how it goes. Thanks to `build.sh` this looks like it could be very easy!

**Comment by ximon18** [comment]
Hmm, I was wrong, killing the process also makes it defunct.

**Comment by ximon18** [comment]
So, on my LXD VM at least, the process hierarchy is as follows (according to `pstree -p -c`):
```
systemd -> containerd -> containerd-shim -> glusterfs-volume-plugin -> glusterfs
```
And it's this `glusterfs` process that becomes defunct. Maybe the issue is that the glusterfs process doesn't have the same process group as the parent glusterfs-volume-plugin instance?

**Comment by ximon18** [comment]
The plugin uses CombinedOutput() as mentioned in [the ticket here](https://stackoverflow.com/questions/46293435/golang-exec-command-cause-a-lot-of-defunct-processes) about defunct processes caused by Go exec.

**Comment by ximon18** [comment]
Note: running `docker plugin disable` on the trajano/glusterfs-docker-volume plugin causes the defunct processes to be reaped.

**Comment by ximon18** [comment]
Maybe the problem is as simple as the plugin not being a single process docker container but launching other processes and not acting as a true PID 1 process so nothing ever reaps the other processes, i.e. use tini or s6 or any of the other Docker mini init implementations?

**Comment by ximon18** [comment]
Yes! I'll submit a PR for using [tini](https://github.com/krallin/tini) as that solved it for me.

**Comment by btheu** [comment]
@ximon18 Your PR have successfully fixed this issue after tests on same condition.

@trajano when this PR will be integrated on master branch for release ?

Best regards,

**Comment by ximon18** [comment]
> @trajano when this PR will be integrated on master branch for release ?

I [suggested](https://github.com/trajano/docker-volume-plugins/pull/30#issuecomment-600255127) that I fork and publish a fixed version of the plugin and @trajano [advised](https://github.com/trajano/docker-volume-plugins/pull/30#issuecomment-600286395) that that is the best way currently to get this fix released.

I'll comment here when the release from my own fork is ready. Thanks @trajano.

**Comment by ximon18** [comment]
*Update:* I'll try and get to publishing my port as soon as I can, some other priorities and the consequences of the global situation got in the way until now. FYI for my own purposes I did already publish a Docker image containing the `tini` patch but there's no published source code for it nor any CI to build it, both of which I want to setup as a proper fork. It's also only the Gluster volume plugin, I'm not sure if I can or should take over the other backend volume plugins as I don't use them, know anything about them nor have a setup to test them. The plugin that I am using is here: https://hub.docker.com/r/ximoneighteen/glusterfs-volume-plugin. Apologies for the delay.
