### ISSUE TITLE
Failed to chmod: operation not permitted

### ISSUE THREAD

**Issue by theit8514** [trajano/docker-volume-plugins#8]
Trying to mount my nas just like I mounted it via the ContainX/docker-volume-netshare plugin, but I'm running into an error. The error occurs because I have "squash root to admin" set on the nas share.

```
# docker -v
Docker version 18.06.0-ce, build 0ffa825
# docker volume create -d trajano/nfs-volume-plugin --name test-data -o device=192.168.200.231:/volume1/nfs-data/docker/test
test-data
# docker run -it -v test-data:/mnt alpine
docker: Error response from daemon: failed to chmod on /var/lib/docker/plugins/80f7d48ff836ead9673bf21f108c684cd5ab867d601a7fac2d0e734bec0e49d2/propagated-mount/bd74903967b14b83bde505cadaf170e44df6587c1fa1df6487b9eb0f29616352: chmod /var/lib/docker/plugins/80f7d48ff836ead9673bf21f108c684cd5ab867d601a7fac2d0e734bec0e49d2/propagated-mount/bd74903967b14b83bde505cadaf170e44df6587c1fa1df6487b9eb0f29616352: operation not permitted.
See 'docker run --help'.
```

Is this a problem in docker? I don't see anywhere in the code where a chmod is taking place.

**Comment by theit8514** [comment]
Sorry, looks like the root folder was not owned by the correct user and nothing could write to it. After updating it to the correct user and setting squashing it works perfectly now.

**Comment by trajano** [comment]
I don't think there's a specific error code that I can use that would give a better explanation.  `operation not permitted` is likely the closest one.
